In [1]:
name="Rajshree"
age=22
college="ABES ENGINEERING COLLEGE"
print(name, age, college)

Rajshree 22 ABES ENGINEERING COLLEGE


# **Numpy**
numpy is a general purpose array processing package, provides a high performance mutli-D arraya object and tools for working with these arrays. it is a fundamentalpackage for scientific computing in python

In [2]:
import numpy as np #np is used as alias for numpy

In [3]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
#multidimensional
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]
arr=np.array([list1, list2, list3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
arr.shape

(3, 5)

In [9]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [10]:
arr.shape

(3, 5)

# **INDEXING**

In [11]:
#accessing the array element
arr=np.array([1,2,3,4,5,6,7,8,9])

In [12]:
arr[3]

np.int64(4)

In [13]:
arr=np.array([list1, list2, list3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
arr[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [15]:
arr=np.arange(0,10)

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr=np.arange(0,10, step=3)
arr

array([0, 3, 6, 9])

In [18]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [19]:
#copy() function and broadcasting
arr[3:]=100
arr

array([  0,   3,   6, 100])

In [20]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#some conditions are very useful in exploratory data analysis
val=2
arr[arr<7]

array([1, 2, 3, 4, 5, 6])

In [22]:
#create arryas and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
arr1=np.arange(0,10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
#The np.ones() function in Python's NumPy library creates a new NumPy array of a specified shape and type, where every element is initialized to 1
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [25]:
np.ones((2,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
#random distribution- in this we get values randomly between [0,1)
np.random.rand(3,3)

array([[0.14447841, 0.56322523, 0.58086605],
       [0.556929  , 0.54547249, 0.39881419],
       [0.97399697, 0.13762699, 0.24201858]])

In [27]:
#randn says that the element can be selected the random variable based on standard normal distribution
arr_ex=np.random.randn(4,4)
arr_ex

array([[ 0.90373478,  0.98910863,  1.82692808,  1.18322387],
       [-1.98403649, -0.64010956,  1.96517022,  0.79541707],
       [-0.74533145,  1.66110457, -0.99380449,  0.42696764],
       [-0.49771324, -1.39109229,  1.53665008, -1.89530296]])

In [28]:
#randint = returns a random integer from a specified range where both endpoints are inclusive
np.random.randint(0,100,8).reshape(4,2) #hhere 8 is the counting of numbers that has to be selected

array([[96, 62],
       [22, 39],
       [96, 37],
       [ 1, 74]], dtype=int32)

In [29]:
#random_sample returns the float value from 0 to 1
np.random.random_sample((1,5))

array([[0.89558096, 0.84075502, 0.07240766, 0.19065936, 0.86823211]])